name: flutter_worker_sniffs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icono-logo-fondo-azul.png
    - assets/image_intro.png

flutter_native_splash:
  color: "#040d26"
  image: assets/image_intro.png
  android: true
  ios: true